config/routes.rb
MadhulataInfotechHrm::Application.routes.draw do
  resources :salary_slips
  resources :leaveapplications
  devise_for :users
  
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  

   root :to => 'leaveapplications#index'

end

app/models/salary_slip.rb
class SalarySlip < ActiveRecord::Base
  attr_accessible :deduction, :employee_detail_id, :gross_salary, :net_salary, :selecttime
  belongs_to :employee_detail
  before_save :total_salary

  def total_salary
  	self.net_salary = self.gross_salary.to_i - self.deduction.to_i
  end
end

app/controllers/salary_slips_controller.rb
class SalarySlipsController < ApplicationController
  before_filter :authenticate_user!
  # GET /salary_slips
  # GET /salary_slips.json
  def index
    @salary_slips = SalarySlip.where(:employee_detail_id => current_user.id)
    #@salary_slips = SalarySlip.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @salary_slips }
    end
  end

  # GET /salary_slips/1
  # GET /salary_slips/1.json
  def show
    @salary_slip = SalarySlip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      # format.pdf { render :text => PDFKit.new( salary_slip_path(@salary_slip) ).to_pdf }
      format.pdf do 
        render :pdf => "show.html.erb"
      end
    end 
  end

  # GET /salary_slips/new
  # GET /salary_slips/new.json
  def new
    @salary_slip = SalarySlip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @salary_slip }
    end
  end

  # GET /salary_slips/1/edit
  def edit
    @salary_slip = SalarySlip.find(params[:id])
  end

  # POST /salary_slips
  # POST /salary_slips.json
  def create
    @salary_slip = SalarySlip.new(params[:salary_slip])

    respond_to do |format|
      if @salary_slip.save
        format.html { redirect_to @salary_slip, notice: 'Salary slip was successfully created.' }
        format.json { render json: @salary_slip, status: :created, location: @salary_slip }               
      else
        format.html { render action: "new" }
        format.json { render json: @salary_slip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /salary_slips/1
  # PUT /salary_slips/1.json
  def update
    @salary_slip = SalarySlip.find(params[:id])

    respond_to do |format|
      if @salary_slip.update_attributes(params[:salary_slip])
        format.html { redirect_to @salary_slip, notice: 'Salary slip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @salary_slip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salary_slips/1
  # DELETE /salary_slips/1.json
  def destroy
    @salary_slip = SalarySlip.find(params[:id])
    @salary_slip.destroy

    respond_to do |format|
      format.html { redirect_to salary_slips_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/salary_slips_helper.rb
module SalarySlipsHelper
end

app/views/salary_slips/_form.html.erb
<%= form_for(@salary_slip) do |f| %>
  <% if @salary_slip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salary_slip.errors.count, "error") %> prohibited this salary_slip from being saved:</h2>

      <ul>
      <% @salary_slip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gross_salary %><br />
    <%= f.text_field :gross_salary %>
  </div>
  <div class="field">
    <%= f.label :deduction %><br />
    <%= f.text_field :deduction %>
  </div>
  <div class="field">
    <%= f.label :net_salary %><br />
    <%= f.text_field :net_salary %>
  </div>
  <div class="field">
    <%= f.label :employee_detail_id %><br />
    <%= f.number_field :employee_detail_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salary_slips/edit.html.erb
<h1>Editing salary_slip</h1>

<%= render 'form' %>

<%= link_to 'Show', @salary_slip %> |
<%= link_to 'Back', salary_slips_path %>

app/views/salary_slips/index.html.erb
<h1>Listing Salary Slips</h1>
<table>
  <tr>
    <th>Gross salary</th>
    <th>Deduction</th>
    <th>Net salary</th>
    <th>Employee detail</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @salary_slips.each do |salary_slip| %>
  <tr>
    <td><%= salary_slip.gross_salary %></td>
    <td><%= salary_slip.deduction %></td>
    <td><%= salary_slip.net_salary %></td>
    <td><%= salary_slip.employee_detail_id %></td>
    <td><%= link_to 'Show', salary_slip %></td>
    <td><%= link_to 'Edit', edit_salary_slip_path(salary_slip) %></td>
    <td><%= link_to 'Destroy', salary_slip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Salary slip', new_salary_slip_path %>

app/views/salary_slips/new.html.erb
<h1>New salary_slip</h1>

<%= render 'form' %>

<%= link_to 'Back', salary_slips_path %>

app/views/salary_slips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Gross Salary:</b>
  <%= @salary_slip.gross_salary %>
</p>

<p>
  <b>Deduction:</b>
  <%= @salary_slip.deduction %>
</p>

<p>
  <b>Net Salary:</b>
  <%= @salary_slip.net_salary %>
</p>
<p><b>Month: <%= @salary_slip.selecttime.strftime("%B") %><%= @salary_slip.selecttime.strftime("%Y") %></p>
<p> <b>Employee Name:</b><%= EmployeeDetail.find(@salary_slip.employee_detail_id).name %></p>
<p> <b>Salary Account No:</b><%= EmployeeDetail.find(@salary_slip.employee_detail_id).account_no %></p>
<p> <b> Date of Joining:</b>
<%= EmployeeDetail.find(@salary_slip.employee_detail_id).join_date.strftime("%Y/%m/%d") %></p>
<p> <b> Employee Id:</b><%= EmployeeDetail.find(@salary_slip.employee_detail_id).sub_unit %></p>
<p> <b>Designations:</b><%= EmployeeDetail.find(@salary_slip.employee_detail_id).job_specification %></p>
<p> <b>Locations:</b><%= EmployeeDetail.find(@salary_slip.employee_detail_id).location %></p>


<%= link_to 'Back', salary_slips_path %><br/>
<%= link_to "pdf format", salary_slip_path(@salary_slip, :format => 'pdf') %>
 

app/views/salary_slips/show.pdf.erb
<%= wicked_pdf_stylesheet_link_tag "documents" %>
<p id="notice"><%= notice %></p>

<p>
  <b>Gross Salary:</b>
  <%= @salary_slip.gross_salary %>
</p>

<p>
  <b>Deduction:</b>
  <%= @salary_slip.deduction %>
</p>

<p>
  <b>Net Salary:</b>
  <%= @salary_slip.net_salary %>
</p>
<p><b>Month: <%= @salary_slip.selecttime.strftime("%B") %><%= @salary_slip.selecttime.strftime("%Y") %></p>
<p> <b>Employee Name:</b><%= EmployeeDetail.find(@salary_slip.employee_detail_id).name %></p>
<p> <b>Salary Account No:</b><%= EmployeeDetail.find(@salary_slip.employee_detail_id).account_no %></p>
<p> <b> Date of Joining:</b>
<%= EmployeeDetail.find(@salary_slip.employee_detail_id).join_date.strftime("%Y/%m/%d") %></p>
<p> <b> Employee Id:</b><%= EmployeeDetail.find(@salary_slip.employee_detail_id).sub_unit %></p>
<p> <b>Designations:</b><%= EmployeeDetail.find(@salary_slip.employee_detail_id).job_specification %></p>
<p> <b>Locations:</b><%= EmployeeDetail.find(@salary_slip.employee_detail_id).location %></p>