config/routes.rb
MadhulataInfotechHrm::Application.routes.draw do
  resources :salary_slips
  resources :leaveapplications
  devise_for :users
  
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  

   root :to => 'leaveapplications#index'

end

app/models/leaveapplication.rb
class Leaveapplication < ActiveRecord::Base
  attr_accessible :comment, :description, :from, :leavetype, :name, :subject, :to,
   :user_id,:employee_detail_id, :commentonleave 
  belongs_to :user
  belongs_to :employee_detail

  def prashant
  	Time.now
  end

end

app/controllers/leaveapplications_controller.rb
class LeaveapplicationsController < ApplicationController
  before_filter :authenticate_user!
  # GET /leaveapplications
  # GET /leaveapplications.json
  def index
    @leaveapplications = Leaveapplication.where(:user_id => current_user.id)
    @leaveapplication = Leaveapplication.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leaveapplications }
    end
  end

  # GET /leaveapplications/1
  # GET /leaveapplications/1.json
  def show
    @leaveapplication = Leaveapplication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @leaveapplication }
    end
  end

  # GET /leaveapplications/new
  # GET /leaveapplications/new.json
  def new
    @leaveapplication = Leaveapplication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @leaveapplication }
    end
  end

  # GET /leaveapplications/1/edit
  def edit
    @leaveapplication = Leaveapplication.find(params[:id])
  end

  # POST /leaveapplications
  # POST /leaveapplications.json
  def create
    @leaveapplication = Leaveapplication.new(params[:leaveapplication])
    @leaveapplication.name = current_user.name
    @leaveapplication.user_id = current_user.id
    @leaveapplication.employee_detail_id = current_user.id
    @leaveapplication.comment = "Pending"
    respond_to do |format|
      if @leaveapplication.save
        Notifier.sending_request(@leaveapplication).deliver
        format.html { redirect_to leaveapplications_path, notice: 'Leaveapplication was successfully created.' }
        format.json { render json: @leaveapplication, status: :created, location: @leaveapplication }
      else
        format.html { render action: "new" }
        format.json { render json: @leaveapplication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leaveapplications/1
  # PUT /leaveapplications/1.json
  def update
    @leaveapplication = Leaveapplication.find(params[:id])

    respond_to do |format|
      if @leaveapplication.update_attributes(params[:leaveapplication])
        format.html { redirect_to @leaveapplication, notice: 'Leaveapplication was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @leaveapplication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaveapplications/1
  # DELETE /leaveapplications/1.json
  def destroy
    @leaveapplication = Leaveapplication.find(params[:id])
    @leaveapplication.destroy

    respond_to do |format|
      format.html { redirect_to leaveapplications_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/leaveapplications_helper.rb
module LeaveapplicationsHelper
 
end

app/views/leaveapplications/_errortype.html.erb
<b> We are waiting for approval </b>

app/views/leaveapplications/_form.html.erb
<%= form_for(@leaveapplication) do |f| %>
  <% if @leaveapplication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leaveapplication.errors.count, "error") %> prohibited this leaveapplication from being saved:</h2>

      <ul>
      <% @leaveapplication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="field">
    <%= f.label :from %><br />
    <%= f.date_select :from %>
  </div>
  <div class="field">
    <%= f.label :to %><br />
    <%= f.date_select :to %>
  </div>
  <div class="field">
    <%= f.label :Leave_Type %><br />
    <%= f.select :leavetype,:collection => [" ","C.L.", "P.L.","LWP", "LOP", "Others"]  %>
  </div>
 
  <div class="field">
    <%= f.label :Reason %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :Emergency_contact_Number %><br />
    <%= f.text_field :description %>
  </div>
  
   <%= f.hidden_field :comment %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leaveapplications/edit.html.erb
<h1>Editing leaveapplication</h1>

<%= render 'form' %>

<%= link_to 'Show', @leaveapplication %> |
<%= link_to 'Back', leaveapplications_path %>

app/views/leaveapplications/index.html.erb
<h1>Listing Leave Applications</h1>
<b>Time: </b><%= @leaveapplication.prashant %><br/>
 <% if EmployeeDetail.find(current_user.id).join_date == nil %>
       <%= render :partial => 'errortype' %>
   <% else %>
   <b>Joining Date:</b><%= join_date.strftime("%Y/%m/%d") %><br/>
 <!--  <b>Total Days:</b><%#= total_day %><br/> -->
   <b>Casual Leave:</b> <%= casual_leave %><br/>
   <b>Priviledge Leave: </b><%= priviledge_leave %><br/> 
   <b>Total Leave: </b><%= total_leave %>
<table>
  <tr>
    <th>Leave Type</th>
    <th>From</th>
    <th>To</th>
    <th>Status</th>
    <th>Comment</th>
    <th>Actions</th>
  </tr>

<% @leaveapplications.each do |leaveapplication| %>
  <tr>
    <!-- <td><%= leaveapplication.name %></td> -->
    <!-- <td><%= leaveapplication.subject %></td> -->
   <!--  <td><%= leaveapplication.description %></td> -->
  <!--  <th><%#= @leaveapplication.casual_leave %></th>
  <th><%#= @leaveapplication.previlege_leave %></th> -->
    <td><%= leaveapplication.leavetype %></td>
    <td><%= leaveapplication.from.strftime("%d/%m/%y") %></td>
    <td><%= leaveapplication.to.strftime("%d/%m/%y") %></td>
    <td><%= leaveapplication.comment %></td>
    <td><%= leaveapplication.commentonleave %></td>
    <td><%= link_to 'Show', leaveapplication %></td>
    
  </tr
<% end %>
</table>

<br />
<button id="test">Apply for leave </button>

<div id="abc">
   <%= render :partial => 'form' %>
</div>
<% end %>

<script>
$(document).ready(function(){
  $("#test").click(function(){
    $("#abc").show();
     });
    });
</script>

app/views/leaveapplications/new.html.erb
<h1>New leaveapplication</h1>

<%= render 'form' %>

<%= link_to 'Back', leaveapplications_path %>

app/views/leaveapplications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @leaveapplication.name %>
</p>

<p>
  <b>Subject:</b>
  <%= @leaveapplication.subject %>
</p>

<p>
  <b>Description:</b>
  <%= @leaveapplication.description %>
</p>

<p>
  <b>Leave Type:</b>
  <%= @leaveapplication.leavetype %>
</p>

<p>
  <b>From:</b>
  <%= @leaveapplication.from %>
</p>

<p>
  <b>To:</b>
  <%= @leaveapplication.to %>
</p>

<p>
  <b>Status:</b>
  <%= @leaveapplication.comment %>
</p>


<%= link_to 'Edit', edit_leaveapplication_path(@leaveapplication) %> |
<%= link_to 'Back', leaveapplications_path %>